[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/shop"
  to = "/shop.html"
  status = 200

[[redirects]]
  from = "/product"
  to = "/product.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200
